### ISSUE TITLE
Add lawful `Semigroup` and `Monoid` instances to `Treap` and `RTreap`

### ISSUE THREAD

**Issue by chshersh** [chshersh/treap#25]
I think `merge` can be an implementation of `<>`.

**Comment by sphaso** [comment]
@chshersh do you mind if I take this?

**Comment by chshersh** [comment]
@sphaso Sure, go for it! It would be also nice to implement property-based testing for `Semigroup` and `Monoid` laws. But we have separate issue for that: #24. Let me know if you want to implement these two property-tests as well 🙂

**Comment by sphaso** [comment]
@chshersh great idea! I opened a PR which includes a couple of property-based tests.
